project_id = "fevrdqmqmbahmeaymplq"

[functions.daily-room]
verify_jwt = false

[functions.validate-pix-receipt]
verify_jwt = false

[functions.connect-onboarding]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.stripe-connect-webhook]
verify_jwt = false
