project_id = "fevrdqmqmbahmeaymplq"

[functions.get-teleconsultation]
verify_jwt = false

[functions.validate-pix-receipt]
verify_jwt = false

[functions.manage-booking]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-push-reminder]
verify_jwt = false

[functions.log-redirect-audit]
verify_jwt = false

