// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-patients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patients_default = defineTool({
  name: "list_patients",
  title: "List patients",
  description: "List the signed-in professional's patients (name, contact, created_at).",
  inputSchema: {
    limit: z.number().int().min(1).max(200).default(50).describe("Max rows to return"),
    search: z.string().trim().optional().describe("Optional case-insensitive name filter")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client(ctx).from("patients").select("id, name, email, phone, created_at").order("created_at", { ascending: false }).limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_appointments_default = defineTool2({
  name: "list_appointments",
  title: "List appointments",
  description: "List the signed-in professional's appointments within an optional date range.",
  inputSchema: {
    from: z2.string().optional().describe("ISO date (YYYY-MM-DD) \u2014 lower bound, inclusive"),
    to: z2.string().optional().describe("ISO date (YYYY-MM-DD) \u2014 upper bound, inclusive"),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client2(ctx).from("appointments").select("id, patient_id, appointment_date, appointment_time, status, notes").order("appointment_date", { ascending: false }).limit(limit);
    if (from) q = q.gte("appointment_date", from);
    if (to) q = q.lte("appointment_date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var financial_summary_default = defineTool3({
  name: "financial_summary",
  title: "Financial summary",
  description: "Aggregate the signed-in professional's income, expenses, and balance from their financial transactions.",
  inputSchema: {
    from: z3.string().optional().describe("ISO date (YYYY-MM-DD) \u2014 lower bound, inclusive"),
    to: z3.string().optional().describe("ISO date (YYYY-MM-DD) \u2014 upper bound, inclusive")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client3(ctx).from("financial_transactions").select("type, amount, transaction_date");
    if (from) q = q.gte("transaction_date", from);
    if (to) q = q.lte("transaction_date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let income = 0;
    let expenses = 0;
    for (const row of data ?? []) {
      const amt = Number(row.amount) || 0;
      if (row.type === "income") income += amt;
      else if (row.type === "expense") expenses += amt;
    }
    const summary = { income, expenses, balance: income - expenses, count: data?.length ?? 0 };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fevrdqmqmbahmeaymplq";
var mcp_default = defineMcp({
  name: "salbcare-mcp",
  title: "SALBCARE",
  version: "0.1.0",
  instructions: "Tools for SALBCARE health professionals: read patients, appointments, and financial summaries scoped to the signed-in user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_patients_default, list_appointments_default, financial_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
